### ISSUE TITLE
Source Text

### ISSUE THREAD

**Issue by gasyoun** [svenkatreddy/Ramayana_Book#29]
@svenkatreddy what a great work. What is the source text? Parab 1888?

**Comment by svenkatreddy** [comment]
Thanks, Here is the source : https://sa.wikiquote.org/wiki/%E0%A4%AF%E0%A5%81%E0%A4%A6%E0%A5%8D%E0%A4%A7%E0%A4%95%E0%A4%BE%E0%A4%A3%E0%A5%8D%E0%A4%A1

**Comment by gasyoun** [comment]
Got it. It itself does not documents the source.
